export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";


export const GET_TRACK_SUCCESS = "GET_TRACK_SUCCESS";
export const GET_TRACK_FAILURE = "GET_TRACK_FAILURE";

export const REQUEST = "REQUEST";

export const CHANGE_ARTIST_NAME_TITLE = "CHANGE_ARTIST_NAME_TITLE";
export const CHANGE_ALBUM_NAME_TITLE = "CHANGE_ALBUM_NAME_TITLE";
