export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";


export const GET_TRACK_SUCCESS = "GET_TRACK_SUCCESS";
export const GET_TRACK_FAILURE = "GET_TRACK_FAILURE";

export const REQUEST = "REQUEST";

export const CHANGE_ARTIST_NAME_TITLE = "CHANGE_ARTIST_NAME_TITLE";
export const CHANGE_ALBUM_NAME_TITLE = "CHANGE_ALBUM_NAME_TITLE";

export const CHANGE_USERNAME_INPUT_VALUE = "CHANGE_USERNAME_INPUT_VALUE";
export const CHANGE_PASSWORD_INPUT_VALUE = "CHANGE_PASSWORD_INPUT_VALUE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CHANGE_USERNAME_LOGIN_INPUT_VALUE = "CHANGE_USERNAME_LOGIN_INPUT_VALUE";
export const CHANGE_PASSWORD_LOGIN_INPUT_VALUE = "CHANGE_PASSWORD_LOGIN_INPUT_VALUE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_TRACK_HISTORY_SUCCESS = "ADD_TO_TRACK_HISTORY_SUCCESS";
export const ADD_TRACK_HISTORY_FAILURE = "ADD_TRACK_HISTORY_FAILURE";

export const GET_TRACK_HISTORY_SUCCESS = "GET_TRACK_HISTORY_SUCCESS";
export const GET_TRACK_HISTORY_FAILURE = "GET_TRACK_HISTORY_FAILURE";
