export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";


export const GET_TRACK_SUCCESS = "GET_TRACK_SUCCESS";
export const GET_TRACK_FAILURE = "GET_TRACK_FAILURE";

export const REQUEST = "REQUEST";

export const CHANGE_ARTIST_NAME_TITLE = "CHANGE_ARTIST_NAME_TITLE";
export const CHANGE_ALBUM_NAME_TITLE = "CHANGE_ALBUM_NAME_TITLE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_TRACK_HISTORY_SUCCESS = "ADD_TO_TRACK_HISTORY_SUCCESS";
export const ADD_TRACK_HISTORY_FAILURE = "ADD_TRACK_HISTORY_FAILURE";

export const ADD_ARTIST_SUCCESS = "ADD_ARTIST_SUCCESS";
export const ADD_ARTIST_FAILURE = "ADD_ARTIST_FAILURE";

export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const ADD_ALBUM_FAILURE = "ADD_ALBUM_FAILURE";

export const ADD_TRACK_SUCCESS = "ADD_TRACK_SUCCESS";
export const ADD_TRACK_FAILURE = "ADD_TRACK_FAILURE";

export const GET_TRACK_HISTORY_SUCCESS = "GET_TRACK_HISTORY_SUCCESS";
export const GET_TRACK_HISTORY_FAILURE = "GET_TRACK_HISTORY_FAILURE";

export const GET_UNPUBLISHED_ITEMS_SUCCESS = "GET_UNPUBLISHED_ITEMS";
export const GET_UNPUBLISHED_ITEMS_FAILURE = "GET_UNPUBLISHED_ITEMS_FAILURE";

export const CHANGE_ARTIST_TO_PUBLISHED_SUCCESS = "CHANGE_ARTIST_TO_PUBLISHED_SUCCESS";
export const CHANGE_ARTIST_TO_PUBLISHED_FAILURE = "CHANGE_ARTIST_TO_PUBLISHED_FAILURE";

export const CHANGE_ALBUM_TO_PUBLISHED_SUCCESS = "CHANGE_ARTIST_TO_PUBLISHED_SUCCESS";
export const CHANGE_ALBUM_TO_PUBLISHED_FAILURE = "CHANGE_ARTIST_TO_PUBLISHED_FAILURE";

export const CHANGE_TRACK_TO_PUBLISHED_SUCCESS = "CHANGE_ARTIST_TO_PUBLISHED_SUCCESS";
export const CHANGE_TRACK_TO_PUBLISHED_FAILURE = "CHANGE_ARTIST_TO_PUBLISHED_FAILURE";

export const DELETE_ARTIST_SUCCESS = "DELETE_ARTIST_SUCCESS";
export const DELETE_ARTIST_FAILURE = "DELETE_ARTIST_FAILURE";

export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAILURE = "DELETE_ALBUM_FAILURE";

export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";
export const DELETE_TRACK_FAILURE = "DELETE_TRACK_FAILURE";
